on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current date and time
      id: current-time
      run: echo "CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    - name: Insert last run time into existing HTML
      run: |
        sed -i 's|<!-- LAST_DEPLOYMENT_TIME -->|${{ env.CURRENT_TIME }}|' index.html # 日付をここで追加する
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
